module.exports = {
  negeerReedsGedaanBool: false,
  schrijfAlleRequestsWeg: true,
  overschrijfAlleRequest: false,
  startDatum: "2020-05-05",
  eindDatum: "2020-05-06",
  volleDebug: false,
  toegestaneClusters: [
    "einde faillissementen",
    "uitspraken faillissement",
    "vereenvoudigde afwikkeling faillissementen",
    "surseances",
    "faillissementen",
    "neerlegging tussentijdse uitdelingslijst in faillissementen",
    "neerlegging slotuitdelingslijst in faillissementen",
  ],
  ontoegestaneClusters: [
    "rectificatie",
    "uitspraken schuldsanering",
    "zittingen in schuldsaneringen",
    "einde schuldsaneringen",
    "neerlegging slotuitdelingslijst in schuldsaneringen",
    "vervanging cur / bwv",
    "einde surseances",
    "uitspraken surseance",
    "schuldsaneringen",
    "zittingen in faillissementen",
  ],
};
