# This is a basic workflow to help you get started with Actions

name: Plesk-notification

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ping-plesk:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Webhook
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: https://vps-284144-5452.hosted.at.hostnet.nl:8443/modules/git/public/web-hook.php?uuid=be9c87da-ec58-f200-caba-42ab4dd87f0c
        data: "Hello from github actions!"
